//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [Serializable]
    [XmlRoot("Factura")]
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.GuiaDespacho = new HashSet<GuiaDespacho>();
            this.SolicitudServicio = new HashSet<SolicitudServicio>();
            this.StockProducto = new HashSet<StockProducto>();
        }

        [XmlElement("nrofac")]
        public int nrofac { get; set; }

        [XmlElement("fechafac")]
        public System.DateTime fechafac { get; set; }

        [XmlElement("descfac")]
        public string descfac { get; set; }

        [XmlElement("monto")]
        public int monto { get; set; }

        [XmlElement("idprod")]
        public int idprod { get; set; }

        [XmlElement("rutcli")]
        public string rutcli { get; set; }

        [XmlElement("Producto")]
        public virtual Producto Producto { get; set; }

        [XmlElement("PerfilUsuario")]
        public virtual PerfilUsuario PerfilUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [XmlElement("GuiaDespacho")]
        public virtual ICollection<GuiaDespacho> GuiaDespacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [XmlElement("SolicitudServicio")]
        public virtual ICollection<SolicitudServicio> SolicitudServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [XmlElement("StockProducto")]
        public virtual ICollection<StockProducto> StockProducto { get; set; }
    }
}
