# Usa una imagen de tiempo de ejecución oficial de MySQL como imagen padre
FROM mysql:latest

# Establece la contraseña de root para el servidor de MySQL
ENV MYSQL_ROOT_PASSWORD=my-secret-pw

# Copia el script de inicialización de la base de datos al contenedor
COPY ./mydatabase.sql /docker-entrypoint-initdb.d/

# Establece la base de datos de MySQL por defecto a utilizar
ENV MYSQL_DATABASE=mydatabase

# Expone el puerto del servidor de MySQL
EXPOSE 3306
