# Generated by Django 3.1.2 on 2021-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Contraseña'),
        ),
    ]
