# Generated by Django 3.2.4 on 2021-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_profile_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=800000, max_digits=35, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
