# Generated by Django 4.1.8 on 2023-06-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='apeusu',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nomusu',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pwd',
        ),
        migrations.AlterField(
            model_name='anwolistaproducto',
            name='reservadoba',
            field=models.CharField(choices=[('S', 'Reservado'), ('N', 'No reservado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='guiadespacho',
            name='estadogd',
            field=models.CharField(choices=[('En bodega', 'En bodega'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipousu',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Técnico', 'Técnico'), ('Bodeguero', 'Bodeguero'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descprod',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idprod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Prod'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nomprod',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='estadosol',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Modificada', 'Modificada'), ('Cerrada', 'Cerrada'), ('Anulada', 'Anulada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='tiposol',
            field=models.CharField(choices=[('Instalación', 'Instalación'), ('Mantención', 'Mantención'), ('Reparación', 'Reparación')], max_length=50),
        ),
    ]
