//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.GuiaDespacho = new HashSet<GuiaDespacho>();
            this.SolicitudServicio = new HashSet<SolicitudServicio>();
            this.StockProducto = new HashSet<StockProducto>();
        }
    
        public int nrofac { get; set; }
        public System.DateTime fechafac { get; set; }
        public string descfac { get; set; }
        public int monto { get; set; }
        public int idprod { get; set; }
        public string rutcli { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual PerfilUsuario PerfilUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuiaDespacho> GuiaDespacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudServicio> SolicitudServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockProducto> StockProducto { get; set; }
    }
}
