//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.VentaBA.ServicioProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BcProducto", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class BcProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HayErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Producto[] ListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HayErrores {
            get {
                return this.HayErroresField;
            }
            set {
                if ((this.HayErroresField.Equals(value) != true)) {
                    this.HayErroresField = value;
                    this.RaisePropertyChanged("HayErrores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Producto[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Factura[] FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.GuiaDespacho[] GuiaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.StockProducto[] StockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descprodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomprodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Factura[] Factura {
            get {
                return this.FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturaField, value) != true)) {
                    this.FacturaField = value;
                    this.RaisePropertyChanged("Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.GuiaDespacho[] GuiaDespacho {
            get {
                return this.GuiaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.GuiaDespachoField, value) != true)) {
                    this.GuiaDespachoField = value;
                    this.RaisePropertyChanged("GuiaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.StockProducto[] StockProducto {
            get {
                return this.StockProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.StockProductoField, value) != true)) {
                    this.StockProductoField = value;
                    this.RaisePropertyChanged("StockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descprod {
            get {
                return this.descprodField;
            }
            set {
                if ((object.ReferenceEquals(this.descprodField, value) != true)) {
                    this.descprodField = value;
                    this.RaisePropertyChanged("descprod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprod {
            get {
                return this.idprodField;
            }
            set {
                if ((this.idprodField.Equals(value) != true)) {
                    this.idprodField = value;
                    this.RaisePropertyChanged("idprod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomprod {
            get {
                return this.nomprodField;
            }
            set {
                if ((object.ReferenceEquals(this.nomprodField, value) != true)) {
                    this.nomprodField = value;
                    this.RaisePropertyChanged("nomprod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class Factura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.GuiaDespacho[] GuiaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.PerfilUsuario PerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Producto ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.SolicitudServicio[] SolicitudServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.StockProducto[] StockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descfacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechafacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nrofacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutcliField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.GuiaDespacho[] GuiaDespacho {
            get {
                return this.GuiaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.GuiaDespachoField, value) != true)) {
                    this.GuiaDespachoField = value;
                    this.RaisePropertyChanged("GuiaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.PerfilUsuario PerfilUsuario {
            get {
                return this.PerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilUsuarioField, value) != true)) {
                    this.PerfilUsuarioField = value;
                    this.RaisePropertyChanged("PerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.SolicitudServicio[] SolicitudServicio {
            get {
                return this.SolicitudServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudServicioField, value) != true)) {
                    this.SolicitudServicioField = value;
                    this.RaisePropertyChanged("SolicitudServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.StockProducto[] StockProducto {
            get {
                return this.StockProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.StockProductoField, value) != true)) {
                    this.StockProductoField = value;
                    this.RaisePropertyChanged("StockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descfac {
            get {
                return this.descfacField;
            }
            set {
                if ((object.ReferenceEquals(this.descfacField, value) != true)) {
                    this.descfacField = value;
                    this.RaisePropertyChanged("descfac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechafac {
            get {
                return this.fechafacField;
            }
            set {
                if ((this.fechafacField.Equals(value) != true)) {
                    this.fechafacField = value;
                    this.RaisePropertyChanged("fechafac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprod {
            get {
                return this.idprodField;
            }
            set {
                if ((this.idprodField.Equals(value) != true)) {
                    this.idprodField = value;
                    this.RaisePropertyChanged("idprod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrofac {
            get {
                return this.nrofacField;
            }
            set {
                if ((this.nrofacField.Equals(value) != true)) {
                    this.nrofacField = value;
                    this.RaisePropertyChanged("nrofac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutcli {
            get {
                return this.rutcliField;
            }
            set {
                if ((object.ReferenceEquals(this.rutcliField, value) != true)) {
                    this.rutcliField = value;
                    this.RaisePropertyChanged("rutcli");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuiaDespacho", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class GuiaDespacho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Factura FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Producto ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadogdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nrofacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nrogdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Factura Factura {
            get {
                return this.FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturaField, value) != true)) {
                    this.FacturaField = value;
                    this.RaisePropertyChanged("Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadogd {
            get {
                return this.estadogdField;
            }
            set {
                if ((object.ReferenceEquals(this.estadogdField, value) != true)) {
                    this.estadogdField = value;
                    this.RaisePropertyChanged("estadogd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprod {
            get {
                return this.idprodField;
            }
            set {
                if ((this.idprodField.Equals(value) != true)) {
                    this.idprodField = value;
                    this.RaisePropertyChanged("idprod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrofac {
            get {
                return this.nrofacField;
            }
            set {
                if ((this.nrofacField.Equals(value) != true)) {
                    this.nrofacField = value;
                    this.RaisePropertyChanged("nrofac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrogd {
            get {
                return this.nrogdField;
            }
            set {
                if ((this.nrogdField.Equals(value) != true)) {
                    this.nrogdField = value;
                    this.RaisePropertyChanged("nrogd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockProducto", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class StockProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Factura FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Producto ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idprodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idstockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nrofacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Factura Factura {
            get {
                return this.FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturaField, value) != true)) {
                    this.FacturaField = value;
                    this.RaisePropertyChanged("Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprod {
            get {
                return this.idprodField;
            }
            set {
                if ((this.idprodField.Equals(value) != true)) {
                    this.idprodField = value;
                    this.RaisePropertyChanged("idprod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idstock {
            get {
                return this.idstockField;
            }
            set {
                if ((this.idstockField.Equals(value) != true)) {
                    this.idstockField = value;
                    this.RaisePropertyChanged("idstock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nrofac {
            get {
                return this.nrofacField;
            }
            set {
                if ((this.nrofacField.Equals(value) != true)) {
                    this.nrofacField = value;
                    this.RaisePropertyChanged("nrofac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilUsuario", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class PerfilUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Factura[] FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.SolicitudServicio[] SolicitudServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apeusuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user auth_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirusuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomusuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipousuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Factura[] Factura {
            get {
                return this.FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturaField, value) != true)) {
                    this.FacturaField = value;
                    this.RaisePropertyChanged("Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.SolicitudServicio[] SolicitudServicio {
            get {
                return this.SolicitudServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudServicioField, value) != true)) {
                    this.SolicitudServicioField = value;
                    this.RaisePropertyChanged("SolicitudServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apeusu {
            get {
                return this.apeusuField;
            }
            set {
                if ((object.ReferenceEquals(this.apeusuField, value) != true)) {
                    this.apeusuField = value;
                    this.RaisePropertyChanged("apeusu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user auth_user {
            get {
                return this.auth_userField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_userField, value) != true)) {
                    this.auth_userField = value;
                    this.RaisePropertyChanged("auth_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dirusu {
            get {
                return this.dirusuField;
            }
            set {
                if ((object.ReferenceEquals(this.dirusuField, value) != true)) {
                    this.dirusuField = value;
                    this.RaisePropertyChanged("dirusu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomusu {
            get {
                return this.nomusuField;
            }
            set {
                if ((object.ReferenceEquals(this.nomusuField, value) != true)) {
                    this.nomusuField = value;
                    this.RaisePropertyChanged("nomusu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                if ((object.ReferenceEquals(this.pwdField, value) != true)) {
                    this.pwdField = value;
                    this.RaisePropertyChanged("pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                if ((object.ReferenceEquals(this.rutField, value) != true)) {
                    this.rutField = value;
                    this.RaisePropertyChanged("rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipousu {
            get {
                return this.tipousuField;
            }
            set {
                if ((object.ReferenceEquals(this.tipousuField, value) != true)) {
                    this.tipousuField = value;
                    this.RaisePropertyChanged("tipousu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudServicio", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class SolicitudServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.Factura FacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.PerfilUsuario PerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descsolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadosolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechavisitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nrofacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nrosolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ruttecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tiposolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.Factura Factura {
            get {
                return this.FacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturaField, value) != true)) {
                    this.FacturaField = value;
                    this.RaisePropertyChanged("Factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.PerfilUsuario PerfilUsuario {
            get {
                return this.PerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilUsuarioField, value) != true)) {
                    this.PerfilUsuarioField = value;
                    this.RaisePropertyChanged("PerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descsol {
            get {
                return this.descsolField;
            }
            set {
                if ((object.ReferenceEquals(this.descsolField, value) != true)) {
                    this.descsolField = value;
                    this.RaisePropertyChanged("descsol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadosol {
            get {
                return this.estadosolField;
            }
            set {
                if ((object.ReferenceEquals(this.estadosolField, value) != true)) {
                    this.estadosolField = value;
                    this.RaisePropertyChanged("estadosol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechavisita {
            get {
                return this.fechavisitaField;
            }
            set {
                if ((this.fechavisitaField.Equals(value) != true)) {
                    this.fechavisitaField = value;
                    this.RaisePropertyChanged("fechavisita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrofac {
            get {
                return this.nrofacField;
            }
            set {
                if ((this.nrofacField.Equals(value) != true)) {
                    this.nrofacField = value;
                    this.RaisePropertyChanged("nrofac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nrosol {
            get {
                return this.nrosolField;
            }
            set {
                if ((this.nrosolField.Equals(value) != true)) {
                    this.nrosolField = value;
                    this.RaisePropertyChanged("nrosol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruttec {
            get {
                return this.ruttecField;
            }
            set {
                if ((object.ReferenceEquals(this.ruttecField, value) != true)) {
                    this.ruttecField = value;
                    this.RaisePropertyChanged("ruttec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tiposol {
            get {
                return this.tiposolField;
            }
            set {
                if ((object.ReferenceEquals(this.tiposolField, value) != true)) {
                    this.tiposolField = value;
                    this.RaisePropertyChanged("tiposol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="auth_user", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class auth_user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.PerfilUsuario[] PerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user_groups[] auth_user_groupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user_user_permissions[] auth_user_user_permissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset date_joinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_staffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_superuserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset last_loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.PerfilUsuario[] PerfilUsuario {
            get {
                return this.PerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilUsuarioField, value) != true)) {
                    this.PerfilUsuarioField = value;
                    this.RaisePropertyChanged("PerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user_groups[] auth_user_groups {
            get {
                return this.auth_user_groupsField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_user_groupsField, value) != true)) {
                    this.auth_user_groupsField = value;
                    this.RaisePropertyChanged("auth_user_groups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user_user_permissions[] auth_user_user_permissions {
            get {
                return this.auth_user_user_permissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_user_user_permissionsField, value) != true)) {
                    this.auth_user_user_permissionsField = value;
                    this.RaisePropertyChanged("auth_user_user_permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset date_joined {
            get {
                return this.date_joinedField;
            }
            set {
                if ((this.date_joinedField.Equals(value) != true)) {
                    this.date_joinedField = value;
                    this.RaisePropertyChanged("date_joined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_active {
            get {
                return this.is_activeField;
            }
            set {
                if ((this.is_activeField.Equals(value) != true)) {
                    this.is_activeField = value;
                    this.RaisePropertyChanged("is_active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_staff {
            get {
                return this.is_staffField;
            }
            set {
                if ((this.is_staffField.Equals(value) != true)) {
                    this.is_staffField = value;
                    this.RaisePropertyChanged("is_staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_superuser {
            get {
                return this.is_superuserField;
            }
            set {
                if ((this.is_superuserField.Equals(value) != true)) {
                    this.is_superuserField = value;
                    this.RaisePropertyChanged("is_superuser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset last_login {
            get {
                return this.last_loginField;
            }
            set {
                if ((this.last_loginField.Equals(value) != true)) {
                    this.last_loginField = value;
                    this.RaisePropertyChanged("last_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="auth_user_groups", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class auth_user_groups : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_group auth_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user auth_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int group_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_group auth_group {
            get {
                return this.auth_groupField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_groupField, value) != true)) {
                    this.auth_groupField = value;
                    this.RaisePropertyChanged("auth_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user auth_user {
            get {
                return this.auth_userField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_userField, value) != true)) {
                    this.auth_userField = value;
                    this.RaisePropertyChanged("auth_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int group_id {
            get {
                return this.group_idField;
            }
            set {
                if ((this.group_idField.Equals(value) != true)) {
                    this.group_idField = value;
                    this.RaisePropertyChanged("group_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="auth_user_user_permissions", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class auth_user_user_permissions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_permission auth_permissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user auth_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int permission_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_permission auth_permission {
            get {
                return this.auth_permissionField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_permissionField, value) != true)) {
                    this.auth_permissionField = value;
                    this.RaisePropertyChanged("auth_permission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user auth_user {
            get {
                return this.auth_userField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_userField, value) != true)) {
                    this.auth_userField = value;
                    this.RaisePropertyChanged("auth_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int permission_id {
            get {
                return this.permission_idField;
            }
            set {
                if ((this.permission_idField.Equals(value) != true)) {
                    this.permission_idField = value;
                    this.RaisePropertyChanged("permission_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="auth_group", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class auth_group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_group_permissions[] auth_group_permissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user_groups[] auth_user_groupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_group_permissions[] auth_group_permissions {
            get {
                return this.auth_group_permissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_group_permissionsField, value) != true)) {
                    this.auth_group_permissionsField = value;
                    this.RaisePropertyChanged("auth_group_permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user_groups[] auth_user_groups {
            get {
                return this.auth_user_groupsField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_user_groupsField, value) != true)) {
                    this.auth_user_groupsField = value;
                    this.RaisePropertyChanged("auth_user_groups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="auth_group_permissions", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class auth_group_permissions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_group auth_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_permission auth_permissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int group_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int permission_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_group auth_group {
            get {
                return this.auth_groupField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_groupField, value) != true)) {
                    this.auth_groupField = value;
                    this.RaisePropertyChanged("auth_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_permission auth_permission {
            get {
                return this.auth_permissionField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_permissionField, value) != true)) {
                    this.auth_permissionField = value;
                    this.RaisePropertyChanged("auth_permission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int group_id {
            get {
                return this.group_idField;
            }
            set {
                if ((this.group_idField.Equals(value) != true)) {
                    this.group_idField = value;
                    this.RaisePropertyChanged("group_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int permission_id {
            get {
                return this.permission_idField;
            }
            set {
                if ((this.permission_idField.Equals(value) != true)) {
                    this.permission_idField = value;
                    this.RaisePropertyChanged("permission_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="auth_permission", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class auth_permission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_group_permissions[] auth_group_permissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_user_user_permissions[] auth_user_user_permissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int content_type_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.django_content_type django_content_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_group_permissions[] auth_group_permissions {
            get {
                return this.auth_group_permissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_group_permissionsField, value) != true)) {
                    this.auth_group_permissionsField = value;
                    this.RaisePropertyChanged("auth_group_permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_user_user_permissions[] auth_user_user_permissions {
            get {
                return this.auth_user_user_permissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_user_user_permissionsField, value) != true)) {
                    this.auth_user_user_permissionsField = value;
                    this.RaisePropertyChanged("auth_user_user_permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codename {
            get {
                return this.codenameField;
            }
            set {
                if ((object.ReferenceEquals(this.codenameField, value) != true)) {
                    this.codenameField = value;
                    this.RaisePropertyChanged("codename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int content_type_id {
            get {
                return this.content_type_idField;
            }
            set {
                if ((this.content_type_idField.Equals(value) != true)) {
                    this.content_type_idField = value;
                    this.RaisePropertyChanged("content_type_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.django_content_type django_content_type {
            get {
                return this.django_content_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.django_content_typeField, value) != true)) {
                    this.django_content_typeField = value;
                    this.RaisePropertyChanged("django_content_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="django_content_type", Namespace="http://schemas.datacontract.org/2004/07/BuenosAires.Model")]
    [System.SerializableAttribute()]
    public partial class django_content_type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string app_labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BuenosAires.VentaBA.ServicioProducto.auth_permission[] auth_permissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string app_label {
            get {
                return this.app_labelField;
            }
            set {
                if ((object.ReferenceEquals(this.app_labelField, value) != true)) {
                    this.app_labelField = value;
                    this.RaisePropertyChanged("app_label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BuenosAires.VentaBA.ServicioProducto.auth_permission[] auth_permission {
            get {
                return this.auth_permissionField;
            }
            set {
                if ((object.ReferenceEquals(this.auth_permissionField, value) != true)) {
                    this.auth_permissionField = value;
                    this.RaisePropertyChanged("auth_permission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HayErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonListaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlGuiaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaGuiaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaPerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaSolicitudServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaStockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlSolicitudServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlStockProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HayErrores {
            get {
                return this.HayErroresField;
            }
            set {
                if ((this.HayErroresField.Equals(value) != true)) {
                    this.HayErroresField = value;
                    this.RaisePropertyChanged("HayErrores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonListaProducto {
            get {
                return this.JsonListaProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonListaProductoField, value) != true)) {
                    this.JsonListaProductoField = value;
                    this.RaisePropertyChanged("JsonListaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonProducto {
            get {
                return this.JsonProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonProductoField, value) != true)) {
                    this.JsonProductoField = value;
                    this.RaisePropertyChanged("JsonProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlFactura {
            get {
                return this.XmlFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlFacturaField, value) != true)) {
                    this.XmlFacturaField = value;
                    this.RaisePropertyChanged("XmlFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlGuiaDespacho {
            get {
                return this.XmlGuiaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlGuiaDespachoField, value) != true)) {
                    this.XmlGuiaDespachoField = value;
                    this.RaisePropertyChanged("XmlGuiaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaFactura {
            get {
                return this.XmlListaFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaFacturaField, value) != true)) {
                    this.XmlListaFacturaField = value;
                    this.RaisePropertyChanged("XmlListaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaGuiaDespacho {
            get {
                return this.XmlListaGuiaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaGuiaDespachoField, value) != true)) {
                    this.XmlListaGuiaDespachoField = value;
                    this.RaisePropertyChanged("XmlListaGuiaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaPerfilUsuario {
            get {
                return this.XmlListaPerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaPerfilUsuarioField, value) != true)) {
                    this.XmlListaPerfilUsuarioField = value;
                    this.RaisePropertyChanged("XmlListaPerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaProducto {
            get {
                return this.XmlListaProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaProductoField, value) != true)) {
                    this.XmlListaProductoField = value;
                    this.RaisePropertyChanged("XmlListaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaSolicitudServicio {
            get {
                return this.XmlListaSolicitudServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaSolicitudServicioField, value) != true)) {
                    this.XmlListaSolicitudServicioField = value;
                    this.RaisePropertyChanged("XmlListaSolicitudServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaStockProducto {
            get {
                return this.XmlListaStockProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaStockProductoField, value) != true)) {
                    this.XmlListaStockProductoField = value;
                    this.RaisePropertyChanged("XmlListaStockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPerfilUsuario {
            get {
                return this.XmlPerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPerfilUsuarioField, value) != true)) {
                    this.XmlPerfilUsuarioField = value;
                    this.RaisePropertyChanged("XmlPerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlProducto {
            get {
                return this.XmlProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlProductoField, value) != true)) {
                    this.XmlProductoField = value;
                    this.RaisePropertyChanged("XmlProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlSolicitudServicio {
            get {
                return this.XmlSolicitudServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlSolicitudServicioField, value) != true)) {
                    this.XmlSolicitudServicioField = value;
                    this.RaisePropertyChanged("XmlSolicitudServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlStockProducto {
            get {
                return this.XmlStockProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlStockProductoField, value) != true)) {
                    this.XmlStockProductoField = value;
                    this.RaisePropertyChanged("XmlStockProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioProducto.IServicioProducto")]
    public interface IServicioProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/ObtenerRespuesta", ReplyAction="http://tempuri.org/IServicioProducto/ObtenerRespuestaResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta ObtenerRespuesta(BuenosAires.VentaBA.ServicioProducto.BcProducto bc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/ObtenerRespuesta", ReplyAction="http://tempuri.org/IServicioProducto/ObtenerRespuestaResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> ObtenerRespuestaAsync(BuenosAires.VentaBA.ServicioProducto.BcProducto bc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/ValidarProducto", ReplyAction="http://tempuri.org/IServicioProducto/ValidarProductoResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta ValidarProducto(BuenosAires.VentaBA.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/ValidarProducto", ReplyAction="http://tempuri.org/IServicioProducto/ValidarProductoResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> ValidarProductoAsync(BuenosAires.VentaBA.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Crear", ReplyAction="http://tempuri.org/IServicioProducto/CrearResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta Crear(BuenosAires.VentaBA.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Crear", ReplyAction="http://tempuri.org/IServicioProducto/CrearResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> CrearAsync(BuenosAires.VentaBA.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/LeerTodos", ReplyAction="http://tempuri.org/IServicioProducto/LeerTodosResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta LeerTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/LeerTodos", ReplyAction="http://tempuri.org/IServicioProducto/LeerTodosResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> LeerTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Leer", ReplyAction="http://tempuri.org/IServicioProducto/LeerResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta Leer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Leer", ReplyAction="http://tempuri.org/IServicioProducto/LeerResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> LeerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Actualizar", ReplyAction="http://tempuri.org/IServicioProducto/ActualizarResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta Actualizar(BuenosAires.VentaBA.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Actualizar", ReplyAction="http://tempuri.org/IServicioProducto/ActualizarResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> ActualizarAsync(BuenosAires.VentaBA.ServicioProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Eliminar", ReplyAction="http://tempuri.org/IServicioProducto/EliminarResponse")]
        BuenosAires.VentaBA.ServicioProducto.Respuesta Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProducto/Eliminar", ReplyAction="http://tempuri.org/IServicioProducto/EliminarResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> EliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProductoChannel : BuenosAires.VentaBA.ServicioProducto.IServicioProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProductoClient : System.ServiceModel.ClientBase<BuenosAires.VentaBA.ServicioProducto.IServicioProducto>, BuenosAires.VentaBA.ServicioProducto.IServicioProducto {
        
        public ServicioProductoClient() {
        }
        
        public ServicioProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta ObtenerRespuesta(BuenosAires.VentaBA.ServicioProducto.BcProducto bc) {
            return base.Channel.ObtenerRespuesta(bc);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> ObtenerRespuestaAsync(BuenosAires.VentaBA.ServicioProducto.BcProducto bc) {
            return base.Channel.ObtenerRespuestaAsync(bc);
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta ValidarProducto(BuenosAires.VentaBA.ServicioProducto.Producto producto) {
            return base.Channel.ValidarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> ValidarProductoAsync(BuenosAires.VentaBA.ServicioProducto.Producto producto) {
            return base.Channel.ValidarProductoAsync(producto);
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta Crear(BuenosAires.VentaBA.ServicioProducto.Producto producto) {
            return base.Channel.Crear(producto);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> CrearAsync(BuenosAires.VentaBA.ServicioProducto.Producto producto) {
            return base.Channel.CrearAsync(producto);
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta LeerTodos() {
            return base.Channel.LeerTodos();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> LeerTodosAsync() {
            return base.Channel.LeerTodosAsync();
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta Leer(int id) {
            return base.Channel.Leer(id);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> LeerAsync(int id) {
            return base.Channel.LeerAsync(id);
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta Actualizar(BuenosAires.VentaBA.ServicioProducto.Producto producto) {
            return base.Channel.Actualizar(producto);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> ActualizarAsync(BuenosAires.VentaBA.ServicioProducto.Producto producto) {
            return base.Channel.ActualizarAsync(producto);
        }
        
        public BuenosAires.VentaBA.ServicioProducto.Respuesta Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioProducto.Respuesta> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
