//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerfilUsuario()
        {
            this.Factura = new HashSet<Factura>();
            this.SolicitudServicio = new HashSet<SolicitudServicio>();
        }
    
        public string rut { get; set; }
        public string tipousu { get; set; }
        public string nomusu { get; set; }
        public string apeusu { get; set; }
        public string correo { get; set; }
        public string dirusu { get; set; }
        public string pwd { get; set; }
        public int user_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }

        [System.Xml.Serialization.XmlIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }

        [System.Xml.Serialization.XmlIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudServicio> SolicitudServicio { get; set; }
    }
}
