//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudServicio
    {
        public int nrosol { get; set; }
        public string tiposol { get; set; }
        public System.DateTime fechavisita { get; set; }
        public string descsol { get; set; }
        public string estadosol { get; set; }
        public int nrofac { get; set; }
        public string ruttec { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual PerfilUsuario PerfilUsuario { get; set; }
    }
}
