//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.Model
{
    using System;
    
    public partial class StockProductoConEstado
    {
        public int idstock { get; set; }
        public int idprod { get; set; }
        public string nomprod { get; set; }
        public Nullable<int> nrofac { get; set; }
        public string estado { get; set; }
    }
}
