# Generated by Django 3.1.2 on 2021-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cuenta', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Correo')),
                ('rut', models.CharField(max_length=80, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
        ),
    ]
