# Generated by Django 3.1.2 on 2021-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(default=123, max_length=80, verbose_name='Contraseña'),
            preserve_default=False,
        ),
    ]
