# Generated by Django 3.2.4 on 2021-07-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210702_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
