# Generated by Django 3.2.4 on 2021-07-02 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_delete_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='PerfilUsuario',
        ),
    ]
